### ISSUE TITLE
Requesting on a sample of how to create a new api

### ISSUE THREAD

**Issue by ShareinSK** [BlackPearSw/fhirball#4]
Hi, 
I am trying to use fhirball for a small project.
I have configured the sample using 'npm install'
When I do a get request `http://localhost:1337/fhir` I am getting a success response.

Now I have created a file by the name sample.js 

    var express  = require('express');
    var router   = express.Router();

    router.get('sample',function(req,res) {
        console.log('Ok');
    });

    module.exports = router;

In the demo.js 

    var app = express();
    app.use('/fhir/', new fhirball.Router(options));

    app.use('/fhir/sample/',require('./sample.js'));  //I have added this line

But when i try `http://localhost:1337/fhir/sample` I am getting a 404 Not found.

    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <title>Error</title>
        </head>
        <body>
            <pre>Cannot GET /fhir/sample</pre>
        </body>
    </html>

Someone pls guide me on the right track.

I am using Postman to test the api.

**Comment by ShareinSK** [comment]
And I would like to know how to use the api's defined in the router module index.js file

**Comment by Dunmail** [comment]
Hi,

The fhirball router partially implements the [HL7 FHIR standard](http://hl7.org/implement/standards/fhir/http.html) for healthcare interoperability. The implementation is based on an old version of the standard (DSTU1), documented [here](http://hl7.org/implement/standards/fhir/2013Sep/http.htm). If you're interested in using this for healthcare then you may be better off looking at newer implementations, for example [fhirbase](https://github.com/fhirbase/fhirbase-plv8).

Looking at your demo code, there are a couple of things to change:

1. The router in `sample.js` handles the `/sample` route, and has been mounted at `/fhir/sample`, so is actually handling requests to: `http://127.0.0.1:1337/fhir/sample/sample`. This is why `GET http://127.0.0.1:1337/fhir/sample` is responding with a 404.

2. sample.js isn't sending a response, so the request hangs. To return a response, change it like this:
````
var express  = require('express');
var router   = express.Router();

router.get('/',function(req,res) {
    res.send('Hello world');
});

module.exports = router;
````

Hope that helps!

**Comment by ShareinSK** [comment]
I noticed that there are a few api's in the router index.js file

https://github.com/BlackPearSw/fhirball/blob/master/lib/Router/index.js

Am I allowed to use those Api's.

How do I access those api's?

I am planning to use this for healthcare application. But I would like to
use MongoDB instead of PostgreSQL.

-
Thanks and Regards,
S.K.Sharein
9444621928

**Comment by Dunmail** [comment]
The fhirball router provides routes as defined by the FHIR Conformance statement passed in the options (the demo uses examples/demo-conformance.js). You're free to use these routes as you see fit

**Comment by ShareinSK** [comment]
I was able to create a patient document using `POST` method url `http://localhost:1337/fhir/patient`.

But now I am trying to update the created data. using `PUT` method url `http://localhost:1337/fhir/patient/59760ae469056f7c20f45e7d`

I have modified only the `date of birth` but when updating getting `412 Precondition Failed`

    {
	"id": "59760ae469056f7c20f45e7d",
        "meta" : {
		"versionId": "0",
		"lastUpdated":"2017-07-24T14:57:40.436Z"
	},
        "resourceType": "Patient",
        "identifier": [
            {
                "label": "NHS",
                "system": "NHS",
                "value": "79455850345"
            }
        ],
        "name": [
             {
                "text": "Mr Shankar",
                "family": [
                    "Shank"
                ],
                "given": [
                    "Shank"
                ],
                "prefix": [
                    "Mr"
                ]
            }
        ],
    "gender": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/v3/vs/AdministrativeGender",
                "code": "M"
            }
        ]
    },
    "birthDate": "1993-08-24T00:00:00.000Z",
    "address": [
        {
            "text": "60 The Drive, Hill, Denholme Clough, West Yorkshire, LS18 3VY",
            "line": [
                "60 The Drive",
                "Hill"
            ],
            "city": "Denholme Clough",
            "state": "West Yorkshire",
            "zip": "LS18 3VY"
        }
    ]
    }

I would like to know which field I am missing. 
Or is there a mistake in the json structure.

I have got the json structure using `read` `http://localhost:1337/fhir/patient/59760ae469056f7c20f45e7d`

**Comment by Dunmail** [comment]
[FHIR DSTU1 spec](http://hl7.org/implement/standards/fhir/2013Sep/http.htm#update)

Implemented in interactions.js, line 204 et seq:
````        
    if (!req.headers['content-location']) {
            return res.status(httpStatus.PRECONDITION_FAILED).end();
        }
````
