### ISSUE TITLE
Unable to load sample data in ubuntu

### ISSUE THREAD

**Issue by ShareinSK** [BlackPearSw/fhirball#5]
@Dunmail 
I am trying to make fhirball work in ubuntu.
Whenever i run node load.js I am getting the following error.

{ [Error: connect ECONNREFUSED 127.0.0.1:1337]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1337 }

In my firewall config I have added the port 1337 but still I keep getting this error.

**Comment by Dunmail** [comment]
You need to have an instance of fhirball listening on 127.0.0.1:1337 before running load.js
